version: '3'

services:
  django:
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
