version: '3'

services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    restart: on-failure
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
