# Generated by Django 4.2.10 on 2024-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="jobs_applied",
        ),
        migrations.AddField(
            model_name="job",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="applied",
            field=models.DateTimeField(),
        ),
    ]
